# Spring Boot configuration
spring:
  application:
    name: rough-copy-spring-boot-rest-api

  # Database properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${DB_PASSWORD} #Change password

    # JPA properties
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #open-in-view: false
    #generate-ddl: true
    properties:
      hibernate:
        format_sql: true

  #Liquibase properties
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yml
    default-schema: public

# Server configuration
server:
  port: 8080