# Spring Boot configuration
spring:
  application:
    name: library

  config:
    import: optional:consul:/
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: library
        health-check-path:  /health


  # Database properties
  datasource:
    #driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres #Change password

    # JPA properties
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #open-in-view: false
    #generate-ddl: true
    properties:
      hibernate:
        format_sql: true

  #Liquibase properties
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.yml
    default-schema: public

  #Kafka properties
  kafka:
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /



# Server configuration
server:
  port: 8080

kafka:
  topic:
    bookReceived: bookReceived