server:
  port: 1000
  error:
    include-message: always
    include-binding-errors: always

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  config:
    import: optional:consul:/
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /health
    gateway:
      routes:
        - id: library-route
          uri: lb://library
          predicates:
            - Path=/api/library/**
          filters:
            - RewritePath=/api/library/(?<remaining>.*), /api/library/${remaining}

        - id: hw_05_1_email_sender-route
          uri: lb://hw_05_1_email_sender
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<remaining>.*), /api/${remaining}

        - id: react-frontend
          uri: http://localhost:3050
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

#GitHub Login
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liX0YscBvVzbDmlw
            client-secret: c1985fa42be6ee54ea208d894d47a866825ecd51

resilience4j:
  circuitbreaker:
    instances:
      services:
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 60
        slow-call-duration-threshold:
          - 2s
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 1


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
