version: '4.3'
services:
  book_management:
    image: postgres:16.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'


#docker-compose -f docker-compose.yaml up -d